[[pages]]
path = "login.py"
name = "Login"
icon = "ğŸ "

[[pages]]
path = "pages/1_ğŸ‘¤_Profil.py"
name = "Profil"
icon = "ğŸ‘¤"

[[pages]]
path = "pages/2_ğŸ§‘â€ğŸ«_Ratgeber.py"
name = "Ratgeber"
icon = ":teacher:"

[[pages]]
path = "pages/3_ğŸ“š_Meine Sammlung.py"
name = "Meine Sammlung"
icon = ":books:"

[[pages]]
path = "pages/entlastungsangebote.py"
name = "Entlastungsangebote"
icon = ""

[[pages]]
path = "pages/vorsorgeauftrag.py"
name = "Vorsorgeauftrag"
icon = ""

[[pages]]
path = "pages/urteilsfaehigkeit.py"
name = "Urteilsfaehigkeit"
icon = ""

[[pages]]
path = "pages/angenehme aktivitaeten gestalten.py"
name = "Angenehme Aktivitaeten gestalten"
icon = ""

[[pages]]
path = "pages/an- und auskleiden.py"
name = "An- und Auskleiden"
icon = ""

[[pages]]
path = "pages/patientenverfuegung.py"
name = "Patientenverfuegung"
icon = ""

[[pages]]
path = "pages/zaehneputzen.py"
name = "Zaehneputzen"
icon = ""

[[pages]]
path = "pages/koerperpflege und toilette.py"
name = "Koerperpflege und Toilette"
icon = ""

[[pages]]
path = "pages/sexualitaet.py"
name = "Sexualitaet"
icon = ""

[[pages]]
path = "pages/weglaufen.py"
name = "Weglaufen"
icon = ""

[[pages]]
path = "pages/essen und trinken.py"
name = "Essen und Trinken"
icon = ""

[[pages]]
path = "pages/inkontinenz.py"
name = "Inkontinenz"
icon = ""

[[pages]]
path = "pages/abklaerung und diagnose.py"
name = "Abklaerung und Diagnose"
icon = ""

[[pages]]
path = "pages/finanzielle ansprueche.py"
name = "Finanzielle Ansprueche"
icon = ""

[[pages]]
path = "pages/autofahren.py"
name = "Autofahren"
icon = ""

[[pages]]
path = "pages/schlafstoerungen.py"
name = "Schlafstoerungen"
icon = ""

[[pages]]
path = "pages/schwierige gespraechssituationen.py"
name = "Schwierige Gespraechssituationen"
icon = ""

[[pages]]
path = "pages/schmerzen.py"
name = "Schmerzen"
icon = ""

[[pages]]
path = "pages/umgang mit aggressionen.py"
name = "Umgang mit Aggressionen"
icon = ""

[[pages]]
path = "pages/wohnanpassungen und hilfsmittel.py"
name = "Wohnanpassungen und Hilfsmittel"
icon = ""

[[pages]]
path = "pages/vorsorge und finanzierung.py"
name = "Vorsorge und Finanzierung"
icon = ""

[[pages]]
path = "pages/behandlung.py"
name = "Behandlung"
icon = ""

[[pages]]
path = "pages/sich verstaendigen.py"
name = "Sich verstaendigen"
icon = ""

[[pages]]
path = "pages/unterstuetzung fuer angehoerige.py"
name = "Unterstuetzung fuer Angehoerige"
icon = ""

[[pages]]
path = "pages/nach der diagnose.py"
name = "Nach der Diagnose"
icon = ""

[[pages]]
path = "pages/herausfordernde situationen.py"
name = "Herausfordernde Situationen"
icon = ""

[[pages]]
path = "pages/krankheitswissen demenz.py"
name = "Krankheitswissen Demenz"
icon = ""

[[pages]]
path = "pages/pflege.py"
name = "Pflege und Betreuung"
icon = ""

[[pages]]
path = "pages/alltag aktiv gestalten.py"
name = "Alltag aktiv gestalten"
icon = ""

[[pages]]
path = "pages/achtsamkeitsuebungen.py"
name = "Achtsamkeitsuebungen"
icon = ""

[[pages]]
path = "pages/selbstfuersorge.py"
name = "Selbstfuersorge"
icon = ""

